//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFBSystemApplicatiopn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public Availability()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int AvailabilityID { get; set; }
        public int SportFacilityID { get; set; }
        public int SlotID { get; set; }
        public string Status { get; set; }
    
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual SportFacility SportFacility { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
