//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFBSystemApplicatiopn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsFacilityBookingEntities1 : DbContext
    {
        public SportsFacilityBookingEntities1()
            : base("name=SportsFacilityBookingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Availability> Availabilities { get; set; }
        public DbSet<Booking> Bookings { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<SportFacility> SportFacilities { get; set; }
        public DbSet<SportType> SportTypes { get; set; }
        public DbSet<TimeSlot> TimeSlots { get; set; }
    }
}
