//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFBSystemApplicatiopn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportFacility
    {
        public SportFacility()
        {
            this.Availabilities = new HashSet<Availability>();
        }
    
        public int SportFacilityID { get; set; }
        public int SportTypeID { get; set; }
        public string SportFacilityName { get; set; }
        public string FacilityStatus { get; set; }
        public string Remarks { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual ICollection<Availability> Availabilities { get; set; }
        public virtual SportType SportType { get; set; }
    }
}
